// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrvuiposqqamcuqgudmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxydnVpcG9zcXFhbWN1cWd1ZG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTIwODIsImV4cCI6MjA2ODk4ODA4Mn0.cirxURExbgeNGqHqOWoxYcMuTOwttXlb46RwyYOzljY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});